# Generated by Django 5.2 on 2025-04-29 17:59

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=home.models.Azienda.set_path),
        ),
    ]
